CREATE TABLE suttas (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    uid VARCHAR NOT NULL UNIQUE,
    sutta_ref VARCHAR NOT NULL,
    title VARCHAR NOT NULL,
    content_html VARCHAR NOT NULL
);
