APPDATA_DB_PATH=../../assets-testing/app-assets/appdata.sqlite3
DICTIONARIES_DB_PATH=../../assets-testing/app-assets/dictionaries.sqlite3

all:
	@echo "Make what?"

# appdata-db-reset:
# 	touch ../../assets-testing/app-assets/appdata.sqlite3 && \
# 	rm ../../assets-testing/app-assets/appdata.sqlite3 && \
# 	diesel migration run --database-url ../../assets-testing/app-assets/appdata.sqlite3 --migration-dir ./migrations/appdata/ && \
# 	cd ../../assets-testing/app-assets/ && \
# 	cat suttas.sql | sqlite3 appdata.sqlite3

# dictionaries-db-reset:
# 	touch $(DICTIONARIES_DB_PATH) && \
# 	rm $(DICTIONARIES_DB_PATH) && \
# 	diesel migration run --database-url $(DICTIONARIES_DB_PATH) --migration-dir ./migrations/dictionaries/

# dictionaries-db-schema:
# 	diesel --database-url $(DICTIONARIES_DB_PATH) print-schema > schema_dictionaries.rs

# cd ../../assets-testing/app-assets/ && \
# cat dicts.sql | sqlite3 dictionaries.sqlite3
