// @generated automatically by Diesel CLI.

diesel::table! {
    suttas (id) {
        id -> Integer,
        uid -> Text,
        sutta_ref -> Text,
        nikaya -> Text,
        language -> Text,
        group_path -> Nullable<Text>,
        group_index -> Nullable<Integer>,
        order_index -> Nullable<Integer>,
        sutta_range_group -> Nullable<Text>,
        sutta_range_start -> Nullable<Integer>,
        sutta_range_end -> Nullable<Integer>,
        title -> Nullable<Text>,
        title_ascii -> Nullable<Text>,
        title_pali -> Nullable<Text>,
        title_trans -> Nullable<Text>,
        description -> Nullable<Text>,
        content_plain -> Nullable<Text>,
        content_html -> Nullable<Text>,
        content_json -> Nullable<Text>,
        content_json_tmpl -> Nullable<Text>,
        source_uid -> Nullable<Text>,
        source_info -> Nullable<Text>,
        source_language -> Nullable<Text>,
        message -> Nullable<Text>,
        copyright -> Nullable<Text>,
        license -> Nullable<Text>,
        // created_at -> Nullable<Timestamp>,
        // updated_at -> Nullable<Timestamp>,
        // indexed_at -> Nullable<Timestamp>,
    }
}
